opensearch-project/opensearch-learning-to-rank-base

README.md
=> The original plugin powers Wikimedia, not the fork

CODE_OF_CONDUCT.md, MAINTAINERS.md
Adds gsingers to MAINTAINERS.md and updates to OpenSearch code of conduct
N/A
=> Adding gsingers to MAINTAINERS.md and updating code of conduct

README.md
Updates the formatting of the readme.
=> Updating readme formatting

build.gradle, src/main/plugin-metadata/plugin-security.policy
- Fix a typo in the security policy file
- Reference the security policy file for tests initiated through gradle
This addresses the failing tests listed in #15. It does not remove any dependencies though.
Addresses #15. Possibly closes.
=> Fix tests failing due to JVM security exceptions

.github/CODEOWNERS, MAINTAINERS.md
Completing adding @sstults as a maintainer. CODEOWNERS must be updated with the MAINTAINERS.md file.
=> adding sstults to CODEOWNERS

.gitignore, src/javaRestTest/java/com/o19s/es/ltr/action/BaseIntegrationTest.java, src/main/java/com/o19s/es/ltr/feature/store/index/IndexFeatureStore.java, src/test/java/com/o19s/es/ltr/feature/store/index/IndexFeatureStoreTests.java
Handling non existing features, featuresets and models more gracefully by throwing a ResourceNotFoundException + proper message instead of NullPointerException.
https://github.com/opensearch-project/opensearch-learning-to-rank-base/issues/25
=> 25 npe when featureset not exists

src/javaRestTest/java/com/o19s/es/ltr/action/BaseIntegrationTest.java, src/javaRestTest/java/com/o19s/es/ltr/logging/LoggingIT.java, src/main/java/com/o19s/es/ltr/feature/store/ScriptFeature.java, src/main/java/com/o19s/es/ltr/query/RankerQuery.java, src/main/java/com/o19s/es/ltr/utils/Suppliers.java, src/main/java/com/o19s/es/termstat/TermStatSupplier.java, src/test/java/com/o19s/es/ltr/feature/store/FeatureSupplierTests.java
A candidate fix as discussed in https://github.com/opensearch-project/opensearch-learning-to-rank-base/issues/52. It is implemented using thread locals to share state between nested data structures in order to share common statistics such as the terms stats and feature vector
Fixes: https://github.com/opensearch-project/opensearch-learning-to-rank-base/issues/52
=> Fix data race which can occur when using script and derived expression features with concurrent segment search

build.gradle, gradle.properties, src/main/java/com/o19s/es/ltr/action/LTRStatsAction.java, src/main/java/com/o19s/es/ltr/action/TransportCacheStatsAction.java, src/main/java/com/o19s/es/ltr/action/TransportClearCachesAction.java, src/main/java/com/o19s/es/ltr/query/StoredLtrQueryBuilder.java
Refactorings to build against opensearch version 3.0.0-SNAPSHOT
https://github.com/opensearch-project/opensearch-learning-to-rank-base/issues/64
=> fix: Refactorings to build against opensearch version 3.0.0-SNAPSHOT

src/main/java/com/o19s/es/explore/ExplorerQuery.java, src/main/java/com/o19s/es/explore/PostingsExplorerQuery.java, src/main/java/com/o19s/es/ltr/feature/PrebuiltFeature.java, src/main/java/com/o19s/es/ltr/feature/store/ScriptFeature.java, src/main/java/com/o19s/es/ltr/query/DerivedExpressionQuery.java, src/main/java/com/o19s/es/ltr/query/RankerQuery.java, src/main/java/com/o19s/es/ltr/rest/RestAddFeatureToSet.java, src/main/java/com/o19s/es/ltr/rest/RestCreateModelFromSet.java, src/main/java/com/o19s/es/ltr/rest/RestFeatureManager.java, src/main/java/com/o19s/es/ltr/rest/RestFeatureStoreCaches.java, src/main/java/com/o19s/es/ltr/rest/RestLTRStats.java, src/main/java/com/o19s/es/ltr/rest/RestSearchStoreElements.java, src/main/java/com/o19s/es/ltr/rest/RestStoreManager.java, src/main/java/com/o19s/es/termstat/TermStatQuery.java, src/main/java/org/opensearch/ltr/breaker/LTRCircuitBreakerService.java, src/main/java/org/opensearch/ltr/settings/LTRSettings.java, src/test/java/org/opensearch/ltr/LTRRestTestCase.java, src/test/java/org/opensearch/ltr/settings/LTRSettingsTestIT.java
* Added LTRSettings
* Added tests for settings
* Added LTRSettings.isLTRPluginEnabled check to all Query.createWeight and all BaseRestHandler.prepareRequest implementations
https://github.com/opensearch-project/opensearch-learning-to-rank-base/issues/75
=> Implemented Settings

src/test/java/org/opensearch/ltr/breaker/LTRCircuitBreakerServiceTests.java, src/test/java/org/opensearch/ltr/breaker/MemoryCircuitBreakerTests.java
Fixed some test class names that did not meet the expected naming pattern (*Test instead of *Tests)
=> fix: fixed namings of test classes

src/main/java/com/o19s/es/ltr/LtrQueryParserPlugin.java
Initialization in LtrQueryParserPlugin was missing - fixed
=> fix: added initialization of ltr settings in LtrQueryParserPlugin

src/main/java/com/o19s/es/ltr/LtrQueryParserPlugin.java, src/main/java/com/o19s/es/ltr/stats/suppliers/PluginHealthStatusSupplier.java, src/main/java/com/o19s/es/ltr/stats/suppliers/StoreStatsSupplier.java, src/main/java/org/opensearch/ltr/stats/suppliers/PluginHealthStatusSupplier.java, src/main/java/org/opensearch/ltr/stats/suppliers/StoreStatsSupplier.java, src/main/java/org/opensearch/ltr/stats/suppliers/utils/StoreUtils.java, src/test/java/org/opensearch/ltr/stats/suppliers/PluginHealthStatusSupplierTests.java, src/test/java/org/opensearch/ltr/stats/suppliers/StoreStatsSupplierTests.java, src/test/java/org/opensearch/ltr/stats/suppliers/utils/StoreUtilsTests.java
The feature is expected to
* evaluate the plugin health by checking the state of the circuit breaker
* evaluate the plugin health by checking the health of the indices required for storing plugin-related objects
* returning the plugin health using a traffic-light labeling (red, yellow, green)
* gathering stats about stored features, featuresets and models
https://github.com/opensearch-project/opensearch-learning-to-rank-base/issues/81
=> 81 supplier plugin health and store usage

src/main/java/com/o19s/es/ltr/LtrQueryParserPlugin.java, src/main/java/com/o19s/es/ltr/stats/suppliers/PluginHealthStatusSupplier.java, src/main/java/com/o19s/es/ltr/stats/suppliers/StoreStatsSupplier.java, src/main/java/org/opensearch/ltr/stats/suppliers/PluginHealthStatusSupplier.java, src/main/java/org/opensearch/ltr/stats/suppliers/StoreStatsSupplier.java, src/main/java/org/opensearch/ltr/stats/suppliers/utils/StoreUtils.java, src/test/java/org/opensearch/ltr/stats/suppliers/PluginHealthStatusSupplierTests.java, src/test/java/org/opensearch/ltr/stats/suppliers/StoreStatsSupplierTests.java, src/test/java/org/opensearch/ltr/stats/suppliers/utils/StoreUtilsTests.java
This PR includes some refactorings for comments in https://github.com/opensearch-project/opensearch-learning-to-rank-base/pull/84
=> 81 supplier plugin health and store usage after revert

src/main/java/com/o19s/es/ltr/LtrQueryParserPlugin.java, src/main/java/com/o19s/es/termstat/TermStatQueryBuilder.java, src/main/java/org/opensearch/ltr/rest/RestStatsLTRAction.java, src/main/java/org/opensearch/ltr/stats/suppliers/utils/StoreUtils.java, src/main/java/org/opensearch/ltr/transport/LTRStatsAction.java, src/main/java/org/opensearch/ltr/transport/LTRStatsNodeRequest.java, src/main/java/org/opensearch/ltr/transport/LTRStatsNodeResponse.java, src/main/java/org/opensearch/ltr/transport/LTRStatsNodesResponse.java, src/main/java/org/opensearch/ltr/transport/LTRStatsRequest.java, src/main/java/org/opensearch/ltr/transport/TransportLTRStatsAction.java, src/test/java/org/opensearch/ltr/transport/TransportLTRStatsActionTests.java
As of now, LTRStats are collected, but not accessible via a REST endpoint. The feature is expected to return LTRStats as a map for URL path admin/ltr/stats.
https://github.com/opensearch-project/opensearch-learning-to-rank-base/issues/87
=> feat: #87 implemented rest endpoint to make stats available

.github/workflows/CI.yml, build.gradle
Now the integration tests can be triggered by `./gradlew integTest`
=> Add a custom task integTest to trigger integration tests.

.github/CODEOWNERS, MAINTAINERS.md
I have nominated Yaliang Wu, Jing Zhang, and Rithin Pullela as maintainers, and the current maintainers have voted and approved. They have contributed code important to running the plugin in a large service environment and have contributed elsewhere in the OpenSearch project.
=> Adding Yaliang Wu, Jing Zhang, and Rithin Pullela as maintainers

.github/workflows/CI.yml
We only need the JAVA 11 and 17 build support in 2.x branch
=> Added builds against JAVA 11 and 17

src/main/java/com/o19s/es/ltr/rest/RestAddFeatureToSet.java, src/main/java/com/o19s/es/ltr/rest/RestCreateModelFromSet.java, src/main/java/com/o19s/es/ltr/rest/RestFeatureManager.java, src/main/java/com/o19s/es/ltr/rest/RestStoreManager.java, src/test/resources/rest-api-spec/test/fstore/10_manage.yml, src/test/resources/rest-api-spec/test/fstore/70_validation.yml, src/test/resources/rest-api-spec/test/fstore/80_search_w_partial_models.yml
Also modified test cases to handle warnings
- The indices that start with .`ltrstore` are considered as system indices. And before accessing the system indices, we need to stash the thread context. Added code to perform context stashing before accessing these indices.
- Modified yaml test cases to handle warnings.
#120
=> Modified Rest Handlers to stash context before modifying system indices

.github/workflows/CI.yml, gradle/wrapper/gradle-wrapper.properties
[Release 3.0] Bump gradle to 8.10.2 and support JDK23
Closes https://github.com/opensearch-project/opensearch-learning-to-rank-base/issues/131
=> [Release 3.0] Bump gradle to 8.10.2 and support JDK23

src/main/java/com/o19s/es/ltr/LtrQueryParserPlugin.java, src/test/resources/rest-api-spec/test/fstore/80_search_w_partial_models.yml
The warning occur flakily.
Refreshing the indices involves accessing `.plugins-ml-config` system index.
=> Modify ITs to ignore transient warning

src/main/java/com/o19s/es/ltr/LtrQueryParserPlugin.java, src/main/java/com/o19s/es/ltr/feature/store/index/IndexFeatureStore.java, src/main/java/com/o19s/es/ltr/rest/RestFeatureManager.java, src/main/java/com/o19s/es/ltr/rest/RestSearchStoreElements.java, src/main/java/com/o19s/es/ltr/rest/RestStoreManager.java, src/test/resources/rest-api-spec/test/fstore/10_manage.yml, src/test/resources/rest-api-spec/test/fstore/80_search_w_partial_models.yml
Stashing context allows get calls to succeed.
The warnings occur flakily.
=> Stash context for GET calls and Modify ITs to ignore transient warnings

src/test/resources/rest-api-spec/test/fstore/80_search_w_partial_models.yml
Instead of refreshing all indices, which could lead to a warning when a system index is refreshed and cause the test to fail due to the unexpected warning, I modified the logic to refresh only the required 'test' index.
=> [Backport to 2.19] Refactor index refresh logic in ITs #135

src/test/resources/rest-api-spec/test/fstore/80_search_w_partial_models.yml
Instead of refreshing all indices, which could lead to a warning when a system index is refreshed and cause the test to fail due to the unexpected warning, I modified the logic to refresh only the required 'test' index.
=> [Backport to 2.x] Refactor index refresh logic in ITs #135

src/test/resources/rest-api-spec/test/fstore/80_search_w_partial_models.yml
Instead of refreshing all indices, which could lead to a warning when a system index is refreshed and cause the test to fail due to the unexpected warning, I modified the logic to refresh only the required 'test' index.
=> Refactor index refresh logic in ITs

src/main/java/com/o19s/es/ltr/LtrQueryParserPlugin.java, src/main/java/com/o19s/es/ltr/ranker/dectree/NaiveAdditiveDecisionTree.java, src/main/java/com/o19s/es/ltr/ranker/parser/XGBoostRawJsonParser.java, src/test/java/com/o19s/es/ltr/ranker/parser/XGBoostRawJsonParserTests.java
Backport of PR: #151 
The LTR plugin is currently using the wrong method of loading xgboost models: it expects the output format of the [get_dump](https://github.com/opensearch-project/opensearch-learning-to-rank-base/pull/get_dump) method, which is only meant for representation purposes e.g. plotting. This PR adds a parser for the output format of the [save_model](https://xgboost.readthedocs.io/en/stable/python/python_api.html#xgboost.Booster.save_model) method.
A quote from the xgboost's documentation:
get_dump: Returns the model dump as a list of strings. Unlike [save_model()](https://xgboost.readthedocs.io/en/stable/python/python_api.html#xgboost.Booster.save_model), the output format is primarily used for visualization or interpretation, hence it’s more human readable but cannot be …
=> [Backport 2.19] Add a model parser for xgboost (for the correct serialization format) (#151)

build.gradle
Use Core's implementation of `httpclient5` and `httpcore5` instead of custom dependency.
Tested on local against remote cluster
=> Address http5client CVE, use core's dependency

build.gradle
Use Core's implementation of `httpclient5` and `httpcore5` instead of custom dependency.
Tested on local against remote cluster
=> [Backport 3.0] Address http5client CVE, use core's dependency (#171)

build.gradle
Use Core's implementation of `httpclient5` and `httpcore5` instead of custom dependency.
=> [Backport 2.19] Address http5client CVE, use core's dependency (#171)

src/test/java/com/o19s/es/ltr/query/LtrQueryTests.java
The issue is that some similarity classes produce varying floating point accuracy. This is mitigated by adjusting ULP, and in this case we are increasing it to 30,000. Specifically this means that there are 30,000 representable floating point numbers between the similarity scores we compare when making our assertions. With a long list of digits to the right of the decimal (as is the case with floats) this doesn't indicate that there's a problem with our logic, so the tests should pass.
#152 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING. …
=> Updating ULP for similarity score comparisons to 30000 to avoid flaky tests

build.gradle, src/main/java/com/o19s/es/ltr/logging/LoggingFetchSubPhase.java
With these latest changes from Core: https://github.com/opensearch-project/OpenSearch/pull/18697 the build of LTR fails with this error:
```
> Task :compileJava
/tmp/tmp7o2tt_my/opensearch-learning-to-rank-base/src/main/java/com/o19s/es/ltr/logging/LoggingFetchSubPhase.java:127: error: cannot find symbol
inspectQuery(qrescore.query())
^
symbol:   method query()
location: variable qrescore of type QueryRescoreContext
/tmp/tmp7o2tt_my/opensearch-learning-to-rank-base/src/main/java/com/o19s/es/ltr/logging/LoggingFetchSubPhase.java:132: error: cannot find symbol
+ qrescore.query().getClass().getSimpleName()
``` 
This PR fixes these errors.
This issue was not surfaced before because it was pulling the older version on opensearch snapshots. Updated the build.gradle to get the latest snapshots …
=> Change QueryRescorer.QueryRescoreContext query processing as per changes in core

build.gradle
Log4j is being included in the plugin jar, which causes jar hell when OpenSearch itself is bundled.
n/a
=> Fix bad inclusion of log4j in this jar when bundled

src/test/java/com/o19s/es/ltr/query/LtrQueryTests.java
Even though we bumped up the ULP to a pretty high number we're still seeing build failures fairly often. After some reading on the subject, it looks like other libraries tend to adopt a hybrid approach that takes into account more nuances of floating point math. See the references section at the top of the [C++ Boost math library](https://www.boost.org/doc/libs/boost_1_75_0/libs/math/doc/html/math_toolkit/float_comparison.html).
So I wrote another analysis tool to do a matrix search of parameters that would pass > 98% of the time but still be reasonably tight. Those parameters are in this commit, as well as the hybrid method that uses them.
n/a
For more information on …
=> Switching to a hybrid method of comparing floats in our assertions
