- MAINTAINERS.md
Rebooting the plugin to make it Awesome!
n/a
> Adding Scott Stults to maintainers list

- build.gradle
- docker/Dockerfile
- docker/local.Dockerfile
- gradle.properties
Sets versions to 2.17.1
Closes #55 
> Setting versions to 2.17.1

- README.md
Adding a link in README for the 2.17.1 release
> Adding link to 2.17.1 release

- README.md
> Update README.md with 2.17.1 release

- src/main/java/com/o19s/es/ltr/LtrQueryParserPlugin.java
- src/main/java/com/o19s/es/ltr/action/TransportAddFeatureToSetAction.java
- src/main/java/com/o19s/es/ltr/action/TransportCreateModelFromSetAction.java
- src/main/java/com/o19s/es/ltr/action/TransportFeatureStoreAction.java
- src/main/java/org/opensearch/ltr/breaker/BreakerName.java
- src/main/java/org/opensearch/ltr/breaker/CircuitBreaker.java
- src/main/java/org/opensearch/ltr/breaker/LTRCircuitBreakerService.java
- src/main/java/org/opensearch/ltr/breaker/MemoryCircuitBreaker.java
- src/main/java/org/opensearch/ltr/breaker/ThresholdCircuitBreaker.java
- src/main/java/org/opensearch/ltr/exception/LimitExceededException.java
- src/test/java/org/opensearch/ltr/breaker/LTRCircuitBreakerServiceTest.java
- src/test/java/org/opensearch/ltr/breaker/MemoryCircuitBreakerTest.java
Implemented circuit breaker as described in https://github.com/opensearch-project/opensearch-learning-to-rank-base/issues/70
> feat: Implemented circuit breaker

- gradle.properties
increased ltrVersion to be consistent with opensearchVersion and suffixed with -SNAPSHOT
> fix: increased ltrVersion

- MAINTAINERS.md
> feat: Added JohannesDaniel in MAINTAINERS.md

- build.gradle
> fix: disabled gradle tasks forbiddenApisTest and testingConventions

- src/main/java/com/o19s/es/ltr/rest/RestAddFeatureToSet.java
- src/main/java/com/o19s/es/ltr/rest/RestCreateModelFromSet.java
- src/main/java/com/o19s/es/ltr/rest/RestFeatureManager.java
- src/main/java/com/o19s/es/ltr/rest/RestStoreManager.java
- src/test/resources/rest-api-spec/test/fstore/10_manage.yml
- src/test/resources/rest-api-spec/test/fstore/70_validation.yml
- src/test/resources/rest-api-spec/test/fstore/80_search_w_partial_models.yml
Also modified test cases to handle warnings
> [Backport 2.19] Modified Rest Handlers to stash context before modifying system indices #126

- src/main/java/com/o19s/es/ltr/feature/store/index/IndexFeatureStore.java
- src/main/java/com/o19s/es/ltr/rest/RestFeatureManager.java
- src/main/java/com/o19s/es/ltr/rest/RestSearchStoreElements.java
- src/main/java/com/o19s/es/ltr/rest/RestStoreManager.java
Stashing context allows get calls to succeed.
> Stashed context for GET calls

- release-notes/opensearch-opensearch-learning-to-rank-base.release-notes-2.19.0.0.md
> Release note for 2.19.0 release

- release-notes/opensearch-opensearch-learning-to-rank-base.release-notes-2.19.0.0.md
> [Backport 2.19] Release note for 2.19.0 release

- release-notes/opensearch-opensearch-learning-to-rank-base.release-notes-2.19.0.0.md
> [Backport 2.x] Release note for 2.19.0 release

- release-notes/opensearch-opensearch-learning-to-rank-base.release-notes-3.0.0.0-alpha1.md
> Added release notes for 3.0-alpha1

- release-notes/opensearch-opensearch-learning-to-rank-base.release-notes-3.0.0.0-beta1.md
Add release note for 3.0 beta1 release
> Add release notes for 3.0 beta1 release

- src/javaRestTest/java/com/o19s/es/ltr/logging/LoggingIT.java
Changes text to match query type
> Fix test to ApproximateScoreQuery

- build.gradle
Part of https://github.com/opensearch-project/opensearch-build/issues/5419
> Increment version to 2.19.2-SNAPSHOT

- build.gradle
Add a task in build.gradle to automate the version increment of opensearch.
> Add update version task

- build.gradle
> [AUTO] Increment version to 3.0.0-SNAPSHOT 3.0 branch

- release-notes/opensearch-opensearch-learning-to-rank-base.release-notes-3.0.0.0.md
> Release notes for LTR 3.0

- .github/workflows/CI.yml
We need to upload code coverage reports for the release project but it doesn't appear we've done that. This should hopefully get us on track.
n/a
> Update CI to upload code coverage report

- src/main/java/com/o19s/es/ltr/Constants.java
- src/main/java/com/o19s/es/ltr/feature/store/StoredLtrModel.java
- src/main/java/com/o19s/es/ltr/query/StoredLtrQueryBuilder.java
- src/main/java/org/opensearch/ltr/transport/LTRStatsNodeResponse.java
- src/main/java/org/opensearch/ltr/transport/LTRStatsRequest.java
- src/test/java/com/o19s/es/ltr/ConstantsTests.java
The 2.19 release had some changes which causes ser/deser issues because of some new fields added and missing version checks for some other fields.
> Fix Version compatibility issues with legacy versions

- src/main/java/com/o19s/es/ltr/Constants.java
- src/main/java/com/o19s/es/ltr/feature/store/StoredLtrModel.java
- src/main/java/com/o19s/es/ltr/query/StoredLtrQueryBuilder.java
- src/main/java/org/opensearch/ltr/transport/LTRStatsNodeResponse.java
- src/main/java/org/opensearch/ltr/transport/LTRStatsRequest.java
- src/test/java/com/o19s/es/ltr/ConstantsTests.java
Fixes version compatibility issues with legacy versions
> [Backport 2.19] Fix Version compatibility issues with legacy versions (#212)

- src/main/java/com/o19s/es/ltr/Constants.java
- src/main/java/com/o19s/es/ltr/feature/store/StoredLtrModel.java
- src/main/java/com/o19s/es/ltr/query/StoredLtrQueryBuilder.java
- src/main/java/org/opensearch/ltr/transport/LTRStatsNodeResponse.java
- src/main/java/org/opensearch/ltr/transport/LTRStatsRequest.java
- src/test/java/com/o19s/es/ltr/ConstantsTests.java
Fixes version compatibility issues with legacy versions
> [Backport 3.0] Fix Version compatibility issues with legacy versions (#212)

- src/main/java/com/o19s/es/ltr/Constants.java
- src/main/java/com/o19s/es/ltr/feature/store/StoredLtrModel.java
- src/main/java/com/o19s/es/ltr/query/StoredLtrQueryBuilder.java
- src/main/java/org/opensearch/ltr/transport/LTRStatsNodeResponse.java
- src/main/java/org/opensearch/ltr/transport/LTRStatsRequest.java
- src/test/java/com/o19s/es/ltr/ConstantsTests.java
Fixes version compatibility issues with legacy versions
> [Backport 3.2] Fix Version compatibility issues with legacy versions (#212)
